---
- name: provision ansibleXdockerXpacker docker image
  hosts: all
  remote_user: root
  become: yes
  become_user: root
  become_method: su
  roles:
    - { role: ansible, character: ansibleXdockerXpacker }
